### PR TITLE
8 shipping history

### PR DESCRIPTION
**Pull request by joshplumley**
Not quite ready yet, but the foundation is in place.

@jarrilla 
1) We dont have a dateCreated in the shipment object. Do we need to make an issue for that? 
2)  is trackingNumber the same as shippingNumber? 
3) I populated the customer in GET shipments/ so that the customerTag is available for the customer column. let me know if you had another way in mind.

The context menu that we add to #4 will be reused here. It is not in this branch yet.

There is a place holder dummy search that searches on the shipping number just to show that works. It will need to be replaced by #11

### CODE REVIEW

**Comment by joshplumley** [comment]
There is a column in this table called **Shipping #**. I didn't know where that data was comping from because when I call the GET /shipments endpoint, I only receive a list of shipments like this:
```{
            "_id": "61df897873e17b166a69e223",
            "customer": {
                "_id": "61d64c2d801996b2a629f4a6",
                "customerTag": "ABC",
                "__v": 0
            },
            "shipmentId": "ABC-SH1",
            "manifest": [
                "61dc1ecae5ae725e72311c91",
                "61dc1ecae5ae725e72311c91"
            ],
            "trackingNumber": "123456",
            "cost": 15.45,
            "__v": 0
        },```

I thought the tracking number might be it. Is **Shipping #** just an increasing number starting at 1 to represent the row number?

**Comment by jarrilla** [comment]
> There is a column in this table called **Shipping #**. I didn't know where that data was coming from because when I call the GET /shipments endpoint, I only receive a list of shipments like this:
> 
> ```
>             "_id": "61df897873e17b166a69e223",
>             "customer": {
>                 "_id": "61d64c2d801996b2a629f4a6",
>                 "customerTag": "ABC",
>                 "__v": 0
>             },
>             "shipmentId": "ABC-SH1",
>             "manifest": [
>                 "61dc1ecae5ae725e72311c91",
>                 "61dc1ecae5ae725e72311c91"
>             ],
>             "trackingNumber": "123456",
>             "cost": 15.45,
>             "__v": 0
>         },
> ```
> 
> I thought the tracking number might be it. Is **Shipping #** just an increasing number starting at 1 to represent the row number?

I don't see "Shipping #". Are you talking about **Shipment #**?

It's meant to be parsed out from shipmentId. E.g. if `shipmentId = 'ABC-SH93'` then shipment # is 93 for that customer-shipment row.

Now that I think about it, it might make more sense to change that table to be
Col 1 - shipment Id
Col 2 - tracking # (or 'LOCAL DELIVERY' | 'CUSTOMER PICKUP' in case it wasn't carrier delivered)
Col 3 - date created (same as now)

I will make this change in the design (will keep it under rev 2)

**Comment by joshplumley** [comment]
Yes that's what I meant. Sounds good!

**Comment by joshplumley** [comment]
@jarrilla Would you be OK with reviewing this WITHOUT the context menu. There a quite a few changes in here and it might easier to review. We can break out the context menu on the shipments history in another issue. If not, I can slap a WIP on it again.

Also, do you have real data to test this MR? I mocked my way through seeing if the pagination worked, but I would like to see how it does with real data.

**Comment by joshplumley** [comment]
Actually hold on, I just realized I need one last thing.

**Comment by joshplumley** [comment]
@jarrilla now ready. I added a clear button to easily clear the search.

**Comment by jarrilla** [comment]
Closes #8 

Merging without context menu.

I removed the `matchOrder` & `matchPart` requirements in order to be able to use pagination on unfiltered data.

See #32 for context menu
See #33 to change default endpoint request

**Pull request merged**
