### PR TITLE
1 packing queue

### LINKED ISSUE #1: Packing Queue
- [x] "Make Packing Slip" button disabled unless a line item is selected
- [x] Line items from different "Orders" should not be able to go in the same packing slip. (If you first select a line from ABC1002, then only other lines from ABC1002 should be selectable)
- [x] Queue Number (~left~right of "Queue") should show number of line items currently in the queue.
- [x] "Fulfilled Qty" tooltip - "This includes number of items that have been packed as well as number of items that have shipped."
- [x] "Show Unfinished Batches" = true -> GET `/workOrders`
- [x] "Show Unfinished Batches" = false -> GET `/workOrders/packingQueue`
- [x] "Search" should filter displayed items by any of "Order #" or "Part"

### PR DESCRIPTION
**Pull request by joshplumley**
closes #1

All functionality is there, but its hard to tell if toggling the checkbox is doing anything since the data from `GET workOrders` and `GET workorders/packingQueue` is the same. You can verify that the right endpoints are being hit from the network tab

The styling will be cleaned up in #15 in an attempt to keep this PR a reasonable size

Screenshot from 2022-01-06 06-50-10

### CODE REVIEW

**Comment by joshplumley** [comment]
@jarrilla

**Comment by jarrilla** [comment]
@joshplumley 

Couple of changes are necessary:
1. Could we make sure search filter ignores case.
2. If line items are selected, and a filter is applied that clears those lines from view, selection status is lost & I am unable to select any other line items until I select & de-select the originally selected line item. (To replicate: select "ABC1001", search "blah", delete search filter)
3. Same behavior as (2) happens if I select, go to History tab, and come back.
4. Minor but annoying: First time clicking "Search" text box after selecting a line-item, the input gets de-selected & I have to click it again.

Regarding (2) & (3), I think it's fine to de-select any line-item that gets filtered but it should also reset whatever state is getting set to prevent cross-order selection.

**Comment by joshplumley** [comment]
@jarrilla I think I addressed you comments.

For 2 and 3, I persisted the selection across those behaviors you mentioned. Let me know if that is OK. We can wipe the selection as well if you prefer. Take this for a spin and let me know what you think.

For 4, I really don't know what is causing that off the top of my head. Would you mind If I made that a different issue to avoid holding up this piece and potentially dealing with more merge conflicts?

**Comment by jarrilla** [comment]
Sounds good. Please see #18 for additional behavior changes of (2 + 3);
And #17 for (4)

**Pull request merged**
