### PR TITLE
persist sort when switching sorts

### LINKED ISSUE #122: Refreshing tab/page resets sort directions
I think this is one of those things that we had already fixed and sloppy merging brought it back.
Hopefully this is the last case of this that we see; sorry!

### PR DESCRIPTION
**Pull request by joshplumley**
closes #122

### CODE REVIEW

**Comment by jarrilla** [comment]
#121 is merged. Could you please review these conflicts @joshplumley ?

**Comment by jbolles94** [comment]
> #121 is merged. Could you please review these conflicts @joshplumley ?

@jarrilla Since Josh is out, I went ahead and addressed the conflicts on this. Let me know if there are any issues.

**Comment by jarrilla** [comment]
It seems this re-introduces the bug that moves a selected row to the top of the table. Otherwise, it looks great! @jbolles94 @joshplumley

**Comment by joshplumley** [comment]
@jarrilla I think this is not working again. Can you please test?

**Comment by jarrilla** [comment]
Sort choice seems to be preserved but actual content does not remain sorted when switching pages/tabs. I.e., it seems that the sort is just not getting triggered when pages are being loaded

**Comment by jarrilla** [comment]
@joshplumley More merge conflicts.

There's also a small issue with shipping history table header. The sorting is preserved but the arrow indicators disappear. That is, the table header does not indicate any sorting, but the content is indeed sorted.

**Comment by joshplumley** [comment]
Yea there is actually a few other things wrong as well. I meant to reach out to tell you to ignore this one for now. Standby.

**Comment by joshplumley** [comment]
OK I believe this is good to review and test again. There were a few other bugs that were caught as well in here.

**Comment by jarrilla** [comment]
@joshplumley 

This seems to introduce a couple bugs
- after creating a package
  - table is not refreshed
  - row disappears from view -- but cycling through filters brings it back up

**Comment by jbolles94** [comment]
> @joshplumley
> 
> This seems to introduce a couple bugs
> 
> * after creating a package
>   
>   * table is not refreshed
>   * ~row disappears from view -- but cycling through filters brings it back up~
> 
> Correction, 2nd bullet is a bug in main

@jarrilla I believe this is fixed. I assumed that by `table is not refreshed` you were referring to the packing queue table since the history table was updating for me. If that is incorrect just let me know. @zhull-jcs is working on the other issue in main.

**Comment by jarrilla** [comment]
Confirmed. Both issues fixed.

**Pull request merged**
