### PR TITLE
5 edit packing slip

### PR DESCRIPTION
**Pull request by jbolles94**
I believe this is good to go, but I am marking this as draft for now until we can test this a little bit since it common'd up some files while cleaning up some errors.

### CODE REVIEW

**Comment by jarrilla** [comment]
I converted it to draft as per your comment.

Let me know when it is ready for review.

**Comment by jbolles94** [comment]
@jarrilla This should be ready for review now. Let me know if anything comes up!

**Review by jarrilla — CHANGES_REQUESTED** [review]
Mostly fine, however when adding new lines to the package, we shouldn't be able to add from different orders; only from the same order this packing slip belongs to. (i.e. `orderNumber` in packing slip model)

The "Order \#" column shouldn't be there in either the viewer (seems to be part of another issue) or the editor.

ref: https://xd.adobe.com/view/2d2ad9d6-10cf-4362-a72c-9cfebb462fc2-7879/

**Comment by jarrilla** [comment]
I updated the tasks in https://github.com/conturo-prototyping/pack-ship-demo/issues/5#issue-1092669714

**Comment by jbolles94** [comment]
@jarrilla Sorry about that! I believe I have addressed all the comments. Let me know if something odd is showing up.

**Comment by jarrilla** [comment]
Looks great!

**Pull request merged**
