### PR TITLE
Split table logic

### LINKED ISSUE #105: Split up table logic
i.e. PackingQueue.jsx is getting very large. Split the tabs so that their more self contained, like the History tab on the Shipping page.

### PR DESCRIPTION
**Pull request by jbolles94**
Closes #105   

This is being marked as draft for now as there are a lot of changes and it should be tested thoroughly for bugs.

### CODE REVIEW

**Comment by jbolles94** [comment]
@jarrilla This should be ready for a review!

**Comment by jarrilla** [comment]
@jbolles94 I went out of order with merging PRs, so this has some conflicts. Could you take a look?

**Comment by jbolles94** [comment]
> @jbolles94 I went out of order with merging PRs, so this has some conflicts. Could you take a look?

@jarrilla I believe all the conflicts have been addressed and this should be ready to go!

**Comment by jarrilla** [comment]
@jbolles94 
"History" tab of shipments page bricks app.

**Comment by jbolles94** [comment]
> @jbolles94 "History" tab of shipments page bricks app.

@jarrilla That's my fault. I accidentally knocked something out of order on some clean up and mistakenly thought it was okay. Should be good now.

**Pull request merged**
