### PR TITLE
124 sort history

### PR DESCRIPTION
**Pull request by jbolles94**

### CODE REVIEW

**Review by jarrilla — CHANGES_REQUESTED** [review]
This bricks Shipment History. No rows show up at all.

**Comment by jbolles94** [comment]
> This bricks Shipment History. No rows show up at all.

@jarrilla Reproducing this was not consistent for me, but I believe I have fixed it. I also noticed some small things with the returned results from the sort that needed fixed so I touched those up as well. Let me know if there are any other issues!

**Comment by joshplumley** [comment]
@jarrilla I think this is not working again. Can you please test?

**Comment by jarrilla** [comment]
It looks like the merge strategy used here overwrites the changes Josh made in #121.
Will have to tag him in for this... @joshplumley

**Comment by joshplumley** [comment]
@jarrilla I think this is good again. The only time typing upon searching is activated is when you have a search active and then you remove the text in BOTH boxes. In that case, the original results will be shown when no search was active. This way there is no mistake when a user erases both text boxes, gets distracted and forgets to press "Search". A user could misconstrued an empty table and empty search boxes as an error, when in fact they just forgot to press search to reinstates the original table results. Anyways, let me know if that is not what you want and we can remove it.

**Pull request merged**
