### PR TITLE
remove part and order search on type

### LINKED ISSUE #117: Suggestion: remove search button on history tab
@jarrilla Currently on the history tab of the shipping page, there is a search button that is initially disabled and then as you type in the order or part number the search takes place and the search button enables. It seems redundant to have both. Easy fix is to remove the search button. However, we could go the other way and remove the searching as we type. What do you think?

### PR DESCRIPTION
**Pull request by joshplumley**
closes #117 

Search only occurs when pressing search button on the history tab of shipment page.

### CODE REVIEW

**Comment by jarrilla** [comment]
@joshplumley 
There's a bug with the shipment history footer. Pagination does not seem to be working. Text is always shown as "1-10 of 10" regardless of how many items there are. Buttons are also ineffective.

**Comment by jbolles94** [comment]
> @joshplumley There's a bug with the shipment history footer. Pagination does not seem to be working. Text is always shown as "1-10 of 10" regardless of how many items there are. Buttons are also ineffective.

@jarrilla This may be fixed by https://github.com/conturo-prototyping/pack-ship-demo/pull/110. When it is merged in and pulled into this branch, we can test this again and see if its fixed. If not, we can look into fixing this here

**Comment by joshplumley** [comment]
Conflicts are resolved and search is no longer active when typing.

**Comment by joshplumley** [comment]
@jarrilla This was the merge from hell, so please double check me on this one. I think I addressed the pagination and maintained the disabled search while typing.

**Comment by jarrilla** [comment]
Update: pagination buttons are still ineffective but at least we can now see total number of items in shipment queue. Will open a new issue against it.

**Pull request merged**
